"""Dashboard landing page (docs/index.html).

Renders a responsive grid of preview cards — one card per subpage — so
a first-time visitor sees every surface at a glance and can click into
the interactive version. Four chart cards embed the matplotlib PNG
thumbnails generated by ``charts.py``; the Calendar and Treatments
cards use inline SVG mock-ups because they don't have a natural PNG
representation.

All four chart cards link to the interactive Plotly pages (`cloud.html`,
`revenue.html`, `capex.html`, `operating_cash_flow.html`). The nav bar
at the top reuses ``_build_nav_html`` so every page on the site shares
the same pill layout; the dashboard lights up the "Home" pill.
"""
from __future__ import annotations

import html
import shutil
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from .interactive_chart import (
    COLORS,
    METRIC_CONFIGS,
    _build_nav_html,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
DB_PATH = REPO_ROOT / "data" / "db" / "capex.db"
DOCS_DIR = REPO_ROOT / "docs"
CHARTS_DIR = REPO_ROOT / "charts"
# Thumbnails are mirrored into docs/ so GitHub Pages (which serves docs/
# as the site root) can resolve them without a ../ escape hatch.
DOCS_CHARTS_DIR = DOCS_DIR / "charts"

# The four chart cards. Order matches the nav pill order so visitors
# land → scan → click with minimal cognitive switching.
CHART_CARDS: list[dict[str, str]] = [
    {
        "metric_key": "cloud_segment_revenue",
        "png": "cloud_revenue_annual.png",
        "subtitle": "Segment revenue for the hyperscaler cloud / datacenter lines.",
        "accent": "#00A4EF",
    },
    {
        "metric_key": "revenue",
        "png": "revenue_annual.png",
        "subtitle": "Top-line revenue across all 13 tracked companies.",
        "accent": "#4285F4",
    },
    {
        "metric_key": "capital_expenditures",
        "png": "capex_annual.png",
        "subtitle": "Capital expenditures from the cash-flow statement.",
        "accent": "#FF9900",
    },
    {
        "metric_key": "operating_cash_flow",
        "png": "operating_cash_flow_annual.png",
        "subtitle": "Operating cash flow — funding capacity for capex.",
        "accent": "#27AE60",
    },
]


def generate_dashboard_html(
    output: str | Path | None = None,
    db_path: str | Path | None = None,
) -> Path:
    """Write the dashboard to `output` (defaults to docs/index.html)."""
    output = Path(output or DOCS_DIR / "index.html")
    output.parent.mkdir(parents=True, exist_ok=True)
    db_path = Path(db_path) if db_path else DB_PATH

    # Mirror thumbnails into the docs/ tree so GitHub Pages can serve
    # them. Keeps the source-of-truth in charts/ for README embedding.
    _mirror_thumbnails(output.parent / "charts")

    stats = _load_stats(db_path)
    nav_html = _build_nav_html("home")
    cards_html = _render_cards()
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html_str = _HTML_TEMPLATE.format(
        nav_html=nav_html,
        cards_html=cards_html,
        company_count=stats["companies"],
        datapoint_count=f"{stats['extractions']:,}",
        latest_filing_date=html.escape(stats["latest_filing_date"] or "—"),
        generated=html.escape(generated),
    )
    output.write_text(html_str, encoding="utf-8")
    return output


def _mirror_thumbnails(dest_dir: Path) -> None:
    """Copy chart PNGs from `charts/` into the dashboard's `charts/` folder.

    Silent on missing PNGs: a chart that hasn't been generated yet simply
    shows the card without a thumbnail (browser's broken-image fallback).
    """
    dest_dir.mkdir(parents=True, exist_ok=True)
    for card in CHART_CARDS:
        src = CHARTS_DIR / card["png"]
        if src.exists():
            shutil.copy2(src, dest_dir / card["png"])


def _load_stats(db_path: Path) -> dict:
    """Tiny summary line: # companies, # extractions, newest filing date.

    Kept defensive so a missing / fresh DB doesn't blow up the
    dashboard render (the page is still useful without the line).
    """
    defaults = {"companies": 0, "extractions": 0, "latest_filing_date": ""}
    if not db_path.exists():
        return defaults
    try:
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        n_co = conn.execute("SELECT COUNT(*) AS n FROM companies").fetchone()
        n_ex = conn.execute("SELECT COUNT(*) AS n FROM extractions").fetchone()
        latest = conn.execute(
            "SELECT MAX(filing_date) AS d FROM source_documents"
        ).fetchone()
        conn.close()
    except sqlite3.Error:
        return defaults
    return {
        "companies": n_co["n"] if n_co else 0,
        "extractions": n_ex["n"] if n_ex else 0,
        "latest_filing_date": (latest["d"] if latest else "") or "",
    }


def _render_cards() -> str:
    pieces = [_render_chart_card(c) for c in CHART_CARDS]
    pieces.append(_render_calendar_card())
    pieces.append(_render_treatments_card())
    return "\n".join(pieces)


def _render_chart_card(card: dict) -> str:
    cfg = METRIC_CONFIGS[card["metric_key"]]
    title = html.escape(cfg["nav_label"])
    subtitle = html.escape(card["subtitle"])
    href = html.escape(cfg["page_name"])
    png = html.escape(f"charts/{card['png']}")
    accent = html.escape(card["accent"])
    return (
        f'<a class="card chart-card" href="{href}" '
        f'style="--accent:{accent};">'
        f'<div class="thumb">'
        f'<img src="{png}" alt="{title} annual chart thumbnail" '
        f'loading="lazy">'
        f'</div>'
        f'<div class="card-body">'
        f'<h2>{title}</h2>'
        f'<p>{subtitle}</p>'
        f'<span class="cta">Open interactive chart →</span>'
        f'</div>'
        f'</a>'
    )


def _render_calendar_card() -> str:
    # A tiny row of "upcoming" tiles + tick marks — styled so it reads
    # as an earnings calendar strip without needing live data.
    accent = "#8E44AD"
    strip = "".join(
        '<span class="cal-tile">'
        f'<span class="cal-dot" style="background:{COLORS.get(t, "#888")};"></span>'
        f'<span class="cal-lbl">{t}</span>'
        '</span>'
        for t in ("AMZN", "MSFT", "GOOGL", "ORCL", "META")
    )
    return (
        f'<a class="card preview-card" href="calendar.html" '
        f'style="--accent:{accent};">'
        f'<div class="thumb thumb-mock">'
        f'<div class="cal-mock">'
        f'<div class="cal-mock-hdr">Upcoming earnings</div>'
        f'<div class="cal-strip">{strip}</div>'
        f'<div class="cal-mock-hdr muted">Recent · last 30 days</div>'
        f'<div class="cal-bars">'
        f'<span class="cal-bar" style="width:80%;"></span>'
        f'<span class="cal-bar" style="width:55%;"></span>'
        f'<span class="cal-bar" style="width:70%;"></span>'
        f'</div>'
        f'</div>'
        f'</div>'
        f'<div class="card-body">'
        f'<h2>Earnings Calendar</h2>'
        f'<p>Upcoming + recent filings across the 13 trackers, with links '
        f'through to each filing on SEC EDGAR / HKEXnews.</p>'
        f'<span class="cta">Open calendar →</span>'
        f'</div>'
        f'</a>'
    )


def _render_treatments_card() -> str:
    accent = "#2E7D32"
    chips = "".join(
        f'<span class="tr-chip" style="background:{COLORS.get(t, "#888")};">'
        f'{t}</span>'
        for t in ("AMZN", "MSFT", "GOOGL", "ORCL", "BABA", "GDS")
    )
    return (
        f'<a class="card preview-card" href="treatments.html" '
        f'style="--accent:{accent};">'
        f'<div class="thumb thumb-mock">'
        f'<div class="tr-mock">'
        f'<div class="tr-mock-hdr">Per-company rules</div>'
        f'<div class="tr-chips">{chips}</div>'
        f'<ul class="tr-bullets">'
        f'<li>Dataset treatments</li>'
        f'<li>Human audit notes</li>'
        f'<li>Restatement policies</li>'
        f'</ul>'
        f'</div>'
        f'</div>'
        f'<div class="card-body">'
        f'<h2>Treatments Audit</h2>'
        f'<p>Full rule book: coverage.yaml structured treatments '
        f'+ human_notes.yaml audit annotations, per company.</p>'
        f'<span class="cta">Open treatments →</span>'
        f'</div>'
        f'</a>'
    )


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NeoCloud CapEx Tracker — dashboard</title>
<style>
  :root {{
    --bg: #fafafa;
    --card-bg: #ffffff;
    --border: #e5e7eb;
    --text: #222;
    --muted: #666;
    --accent: #2E75B6;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    margin: 0; padding: 20px; background: var(--bg); color: var(--text);
  }}
  .nav {{ text-align: center; margin: 0 auto 18px; max-width: 1400px; }}
  .nav-pill {{ display: inline-block; padding: 6px 14px; margin: 0 4px;
    border: 1px solid #888; border-radius: 18px; color: #555; font-size: 13px;
    text-decoration: none; background: #fff; }}
  .nav-pill:hover {{ border-color: #2E75B6; color: #2E75B6; }}
  .nav-pill.active {{ background: #2E75B6; color: #fff; border-color: #2E75B6;
    font-weight: bold; }}
  header.hero {{ max-width: 1200px; margin: 0 auto 22px; text-align: center; }}
  header.hero h1 {{ font-size: 28px; margin: 0 0 6px; }}
  header.hero p {{ color: var(--muted); font-size: 14px; margin: 0; }}
  .grid {{
    display: grid; gap: 18px;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    max-width: 1200px; margin: 0 auto;
  }}
  .card {{
    display: flex; flex-direction: column;
    background: var(--card-bg); border: 1px solid var(--border);
    border-top: 4px solid var(--accent, #2E75B6);
    border-radius: 10px; overflow: hidden;
    text-decoration: none; color: inherit;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04);
    transition: transform 0.15s ease, box-shadow 0.15s ease;
  }}
  .card:hover {{
    transform: translateY(-2px);
    box-shadow: 0 6px 16px rgba(0,0,0,0.08);
  }}
  .thumb {{
    background: #f3f4f6;
    border-bottom: 1px solid var(--border);
    aspect-ratio: 16/9;
    display: flex; align-items: center; justify-content: center;
    overflow: hidden;
  }}
  .thumb img {{
    width: 100%; height: 100%; object-fit: cover; object-position: top;
    display: block;
  }}
  .card-body {{ padding: 14px 18px 18px; }}
  .card-body h2 {{
    margin: 0 0 6px; font-size: 17px; color: var(--accent, #2E75B6);
  }}
  .card-body p {{
    margin: 0 0 10px; font-size: 13px; line-height: 1.45;
    color: var(--text);
  }}
  .cta {{ font-size: 12px; font-weight: 600; color: var(--accent, #2E75B6);
    letter-spacing: 0.02em; }}

  /* Calendar mock */
  .thumb-mock {{ padding: 18px; align-items: flex-start; flex-direction: column;
    justify-content: flex-start; }}
  .cal-mock, .tr-mock {{ width: 100%; }}
  .cal-mock-hdr {{ font-size: 12px; text-transform: uppercase;
    letter-spacing: 0.08em; color: #555; font-weight: 600; margin-bottom: 8px; }}
  .cal-mock-hdr.muted {{ color: #999; margin-top: 12px; }}
  .cal-strip {{ display: flex; flex-wrap: wrap; gap: 6px; }}
  .cal-tile {{ display: inline-flex; align-items: center; gap: 6px;
    background: #fff; border: 1px solid var(--border);
    border-radius: 6px; padding: 4px 8px; font-size: 12px; }}
  .cal-dot {{ width: 8px; height: 8px; border-radius: 50%; display: inline-block; }}
  .cal-lbl {{ color: #444; font-weight: 500; }}
  .cal-bars {{ display: flex; flex-direction: column; gap: 4px;
    margin-top: 6px; }}
  .cal-bar {{ display: block; height: 6px; background: #8E44AD;
    border-radius: 3px; opacity: 0.65; }}

  /* Treatments mock */
  .tr-mock-hdr {{ font-size: 12px; text-transform: uppercase;
    letter-spacing: 0.08em; color: #555; font-weight: 600; margin-bottom: 8px; }}
  .tr-chips {{ display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 12px; }}
  .tr-chip {{ color: #fff; font-size: 11px; font-weight: 600;
    padding: 3px 8px; border-radius: 10px; }}
  .tr-bullets {{ margin: 0; padding-left: 18px; color: #444; font-size: 12px;
    line-height: 1.6; }}

  footer.foot {{
    max-width: 1200px; margin: 28px auto 10px; text-align: center;
    color: var(--muted); font-size: 11px;
  }}
  footer.foot a {{ color: var(--muted); }}

  @media (max-width: 640px) {{
    body {{ padding: 12px; }}
    .grid {{ gap: 12px; grid-template-columns: 1fr; }}
    .card-body {{ padding: 12px 14px 14px; }}
    header.hero h1 {{ font-size: 22px; }}
  }}
</style>
</head>
<body>
{nav_html}
<header class="hero">
  <h1>NeoCloud CapEx Tracker</h1>
  <p>{company_count} companies · {datapoint_count} data points ·
     newest filing {latest_filing_date}</p>
</header>

<div class="grid">
{cards_html}
</div>

<footer class="foot">
  Sources: SEC EDGAR + HKEXnews filings, FX via ECB / frankfurter.app.
  <br>Generated {generated} ·
  <a href="https://github.com/KKKKKKAI/neocloud-capex-tracker">
  source on GitHub</a>
</footer>
</body>
</html>"""
