-- Auto-generated by capex.db.dump — do not edit by hand.
-- Regenerated on every successful DB mutation.
-- Source of truth: data/db/capex.db

BEGIN TRANSACTION;
CREATE TABLE audit_log (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ts           TEXT NOT NULL,
    actor        TEXT NOT NULL,         -- skill name + version, e.g. "sync-companies@0.0.1"
    action       TEXT NOT NULL,         -- e.g. "companies_upsert"
    target_table TEXT NOT NULL,
    target_id    INTEGER,
    payload      TEXT                   -- JSON of what changed
);
INSERT INTO "audit_log" VALUES(1,'2026-04-09T17:47:23+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 1, "total": 1, "updated": 0, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(2,'2026-04-09T17:47:23+00:00','sync-metric-definitions@0.0.1','metric_definitions_sync','metric_definitions',NULL,'{"deleted": 0, "inserted": 5, "total": 5, "updated": 0, "yaml_path": "data/seeds/metric_definitions.yaml"}');
INSERT INTO "audit_log" VALUES(3,'2026-04-09T17:47:58+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 0, "total": 1, "updated": 1, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(4,'2026-04-09T17:47:58+00:00','sync-metric-definitions@0.0.1','metric_definitions_sync','metric_definitions',NULL,'{"deleted": 0, "inserted": 0, "total": 5, "updated": 5, "yaml_path": "data/seeds/metric_definitions.yaml"}');
INSERT INTO "audit_log" VALUES(5,'2026-04-09T18:24:16+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 12, "total": 13, "updated": 1, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(6,'2026-04-09T18:37:24+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 0, "total": 13, "updated": 13, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(7,'2026-04-10T02:30:00+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',1,'{"form_type": "10-K", "period_of_report": "2025-06-30", "raw_path": "data/_sources/MSFT/_raw/msft-20250630.htm", "sha256": "99d693f6c1544144ebeee92954f151a85bc62111837530a42855953bc01d0bbe", "ticker": "MSFT"}');
INSERT INTO "audit_log" VALUES(8,'2026-04-10T02:35:21+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',1,'{"canonical_path": "data/_sources/MSFT/2025/[30.07.2025][MSFT][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "MSFT"}');
INSERT INTO "audit_log" VALUES(9,'2026-04-10T10:31:39+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',2,'{"form_type": "10-K", "period_of_report": "2025-12-31", "raw_path": "data/_sources/AMZN/_raw/amzn-20251231.htm", "sha256": "beb1bfc28558135e76882db0cf36ba72a1ab44e2144fe37534f4da1e120ddb57", "ticker": "AMZN"}');
INSERT INTO "audit_log" VALUES(10,'2026-04-10T10:31:40+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',3,'{"form_type": "10-K", "period_of_report": "2025-12-31", "raw_path": "data/_sources/GOOGL/_raw/goog-20251231.htm", "sha256": "c2f6301004f35411a20611c14ff01d80a85c0bcbab6053c80d8cc7f6fc747161", "ticker": "GOOGL"}');
INSERT INTO "audit_log" VALUES(11,'2026-04-10T10:31:41+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',4,'{"form_type": "10-K", "period_of_report": "2025-12-31", "raw_path": "data/_sources/META/_raw/meta-20251231.htm", "sha256": "97d1a65e8f28c8d2878a1f73218b89f8da3be83e6517c5cffdd81845c8ce40be", "ticker": "META"}');
INSERT INTO "audit_log" VALUES(12,'2026-04-10T10:31:44+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',5,'{"form_type": "10-K", "period_of_report": "2025-05-31", "raw_path": "data/_sources/ORCL/_raw/orcl-20250531.htm", "sha256": "76d67d94d2168379120f9232387f7cb58fe65159e5c4743c470d7fbeee874835", "ticker": "ORCL"}');
INSERT INTO "audit_log" VALUES(13,'2026-04-10T10:31:46+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',6,'{"form_type": "20-F", "period_of_report": "2025-03-31", "raw_path": "data/_sources/BABA/_raw/baba-20250331.htm", "sha256": "7959467eb4e32c27af13f2804aa4d0a7d0d6f49118f2a440b11d12e55eed4c46", "ticker": "BABA"}');
INSERT INTO "audit_log" VALUES(14,'2026-04-10T10:31:48+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',7,'{"form_type": "20-F", "period_of_report": "2025-12-31", "raw_path": "data/_sources/BIDU/_raw/d38065d20f.htm", "sha256": "16a242f31d42b99f202abf7b51317fbc0223732f9136f6f9ec4fe813f2e17ff5", "ticker": "BIDU"}');
INSERT INTO "audit_log" VALUES(15,'2026-04-10T10:31:50+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',8,'{"form_type": "20-F", "period_of_report": "2024-12-31", "raw_path": "data/_sources/GDS/_raw/gds-20241231x20f.htm", "sha256": "c4f419260120887c9b701420a79902557cd9421225785a0e8d4215ae659d2b7c", "ticker": "GDS"}');
INSERT INTO "audit_log" VALUES(16,'2026-04-10T10:31:51+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',9,'{"form_type": "10-K", "period_of_report": "2025-12-31", "raw_path": "data/_sources/CRWV/_raw/crwv-20251231.htm", "sha256": "c796cf3da3deaf213561a54b731af74526ff72fc854fde005591b0b1880ed1fc", "ticker": "CRWV"}');
INSERT INTO "audit_log" VALUES(17,'2026-04-10T10:31:53+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',10,'{"form_type": "10-K", "period_of_report": "2025-05-31", "raw_path": "data/_sources/APLD/_raw/apld-20250531.htm", "sha256": "70bdc8e48e8a7d296e29c84e656f575e1f294f2977cd1a27ab1767ea1caa495e", "ticker": "APLD"}');
INSERT INTO "audit_log" VALUES(18,'2026-04-10T10:31:55+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',11,'{"form_type": "20-F", "period_of_report": "2024-06-30", "raw_path": "data/_sources/IREN/_raw/iren-20240630.htm", "sha256": "f3333fa476c97bc8c1b6a5e069a3a3a9708e49e13e22dd65be400315409a45ab", "ticker": "IREN"}');
INSERT INTO "audit_log" VALUES(19,'2026-04-10T10:31:56+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',12,'{"form_type": "20-F", "period_of_report": "2024-12-31", "raw_path": "data/_sources/NBIS/_raw/nbis-20241231x20f.htm", "sha256": "7edf65f79601be53a61de4bdbdbe954d5671c0c686d6d5bcbca8a091cf17277a", "ticker": "NBIS"}');
INSERT INTO "audit_log" VALUES(20,'2026-04-10T10:33:14+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',2,'{"canonical_path": "data/_sources/AMZN/2025/[06.02.2026][AMZN][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "AMZN"}');
INSERT INTO "audit_log" VALUES(21,'2026-04-10T10:33:16+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',10,'{"canonical_path": "data/_sources/APLD/2025/[30.07.2025][APLD][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "APLD"}');
INSERT INTO "audit_log" VALUES(22,'2026-04-10T10:33:18+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',6,'{"canonical_path": "data/_sources/BABA/2025/[26.06.2025][BABA][AR][20-F].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "BABA"}');
INSERT INTO "audit_log" VALUES(23,'2026-04-10T10:33:19+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',7,'{"canonical_path": "data/_sources/BIDU/2025/[17.03.2026][BIDU][AR][20-F].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "BIDU"}');
INSERT INTO "audit_log" VALUES(24,'2026-04-10T10:33:20+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',9,'{"canonical_path": "data/_sources/CRWV/2025/[02.03.2026][CRWV][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "CRWV"}');
INSERT INTO "audit_log" VALUES(25,'2026-04-10T10:33:22+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',8,'{"canonical_path": "data/_sources/GDS/2024/[28.04.2025][GDS][AR][20-F].htm", "fiscal_year": 2024, "period_token": "AR", "ticker": "GDS"}');
INSERT INTO "audit_log" VALUES(26,'2026-04-10T10:33:23+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',3,'{"canonical_path": "data/_sources/GOOGL/2025/[05.02.2026][GOOGL][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "GOOGL"}');
INSERT INTO "audit_log" VALUES(27,'2026-04-10T10:33:24+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',11,'{"canonical_path": "data/_sources/IREN/2024/[28.08.2024][IREN][AR][20-F].htm", "fiscal_year": 2024, "period_token": "AR", "ticker": "IREN"}');
INSERT INTO "audit_log" VALUES(28,'2026-04-10T10:33:25+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',4,'{"canonical_path": "data/_sources/META/2025/[29.01.2026][META][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "META"}');
INSERT INTO "audit_log" VALUES(29,'2026-04-10T10:33:26+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',12,'{"canonical_path": "data/_sources/NBIS/2024/[30.04.2025][NBIS][AR][20-F].htm", "fiscal_year": 2024, "period_token": "AR", "ticker": "NBIS"}');
INSERT INTO "audit_log" VALUES(30,'2026-04-10T10:33:28+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',5,'{"canonical_path": "data/_sources/ORCL/2025/[18.06.2025][ORCL][AR][10-K].htm", "fiscal_year": 2025, "period_token": "AR", "ticker": "ORCL"}');
INSERT INTO "audit_log" VALUES(31,'2026-04-10T11:56:22+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 0, "total": 13, "updated": 13, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(32,'2026-04-10T11:56:49+00:00','fetch-company-report@0.1.0','source_document_inserted','source_documents',13,'{"form_type": "HK-AR", "period_of_report": "2025-12-31", "raw_path": "data/_sources/0700/_raw/2026040901232_c.pdf", "sha256": "d19f183452e9b8d0c47bcb7543dcbf435b585b2610759b42c0cba7c13f7361c7", "ticker": "0700"}');
INSERT INTO "audit_log" VALUES(33,'2026-04-10T11:57:05+00:00','organize-sources@0.1.0','canonical_path_set','source_documents',13,'{"canonical_path": "data/_sources/0700/2025/[09.04.2026][0700][AR][HK-AR].pdf", "fiscal_year": 2025, "period_token": "AR", "ticker": "0700"}');
INSERT INTO "audit_log" VALUES(34,'2026-04-10T15:38:36+00:00','sync-metric-definitions@0.0.1','metric_definitions_sync','metric_definitions',NULL,'{"deleted": 0, "inserted": 0, "total": 5, "updated": 5, "yaml_path": "data/seeds/metric_definitions.yaml"}');
CREATE TABLE companies (
    ticker                TEXT PRIMARY KEY,
    name                  TEXT NOT NULL,
    preferred_source      TEXT NOT NULL CHECK(preferred_source IN ('sec_edgar', 'hkex')),
    edgar_cik             TEXT,
    hkex_stock_code       TEXT,
    fiscal_year_end_month INTEGER NOT NULL CHECK(fiscal_year_end_month BETWEEN 1 AND 12),
    synced_at             TEXT NOT NULL
);
INSERT INTO "companies" VALUES('MSFT','Microsoft Corporation','sec_edgar','0000789019',NULL,6,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('AMZN','Amazon.com, Inc.','sec_edgar','0001018724',NULL,12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('GOOGL','Alphabet Inc.','sec_edgar','0001652044',NULL,12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('META','Meta Platforms, Inc.','sec_edgar','0001326801',NULL,12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('ORCL','Oracle Corporation','sec_edgar','0001341439',NULL,5,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('BABA','Alibaba Group Holding Limited','sec_edgar','0001577552','9988',3,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('BIDU','Baidu, Inc.','sec_edgar','0001329099','9888',12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('GDS','GDS Holdings Limited','sec_edgar','0001526125','9698',12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('0700','Tencent Holdings Limited','hkex',NULL,'0700',12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('CRWV','CoreWeave, Inc.','sec_edgar','0001769628',NULL,12,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('APLD','Applied Digital Corporation','sec_edgar','0001144879',NULL,5,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('IREN','IREN Limited','sec_edgar','0001878848',NULL,6,'2026-04-10T11:56:22+00:00');
INSERT INTO "companies" VALUES('NBIS','Nebius Group N.V.','sec_edgar','0001513845',NULL,12,'2026-04-10T11:56:22+00:00');
CREATE TABLE extractions (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    source_document_id INTEGER NOT NULL REFERENCES source_documents(id),
    metric_key         TEXT NOT NULL REFERENCES metric_definitions(key),
    value              REAL,            -- nullable for "not disclosed"
    value_text         TEXT,            -- raw text as it appears in the filing
    unit               TEXT NOT NULL,
    quote              TEXT NOT NULL,
    locator_page       INTEGER,
    locator_section    TEXT,
    extraction_type    TEXT NOT NULL CHECK(extraction_type IN ('direct', 'inferred', 'derived')),
    confidence         REAL,
    extracting_model   TEXT NOT NULL,
    protocol_version   TEXT NOT NULL,
    extracted_at       TEXT NOT NULL,
    UNIQUE(source_document_id, metric_key, extracting_model)
);
CREATE TABLE golden_facts (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker            TEXT NOT NULL,
    period            TEXT NOT NULL,
    metric_key        TEXT NOT NULL,
    expected_value    REAL,
    expected_unit     TEXT NOT NULL,
    source_doc_sha256 TEXT NOT NULL,
    note              TEXT,
    UNIQUE(ticker, period, metric_key)
);
CREATE TABLE metric_definitions (
    key          TEXT PRIMARY KEY,
    label        TEXT NOT NULL,
    aliases      TEXT NOT NULL,        -- JSON array
    unit_default TEXT NOT NULL,
    description  TEXT
);
INSERT INTO "metric_definitions" VALUES('capital_expenditures','Capital expenditures','["capex", "capital expenditure", "capital expenditures", "purchases of property and equipment", "additions to property and equipment", "purchases of property, plant and equipment", "property and equipment additions", "investments in property and equipment", "us-gaap:PaymentsToAcquirePropertyPlantAndEquipment"]','USD_millions','Cash outflows for purchases of property, plant, and equipment. Typically reported in the investing activities section of the cash flow statement. This is the headline capex figure.');
INSERT INTO "metric_definitions" VALUES('depreciation_amortization','Depreciation and amortization','["d&a", "depreciation", "depreciation and amortization", "depreciation, amortization and accretion", "depreciation and amortization expense", "us-gaap:DepreciationDepletionAndAmortization"]','USD_millions','Non-cash charge reflecting the periodic expense of long-lived assets. Often reported alongside capex as a proxy for asset base turnover.');
INSERT INTO "metric_definitions" VALUES('property_plant_equipment_net','Property, plant and equipment, net','["ppe", "pp&e", "property and equipment net", "property, plant and equipment, net", "net property and equipment", "us-gaap:PropertyPlantAndEquipmentNet"]','USD_millions','Balance sheet carrying value of long-lived tangible assets after accumulated depreciation. The stock companion to capex (flow) and D&A (flow).');
INSERT INTO "metric_definitions" VALUES('revenue','Total revenue','["revenue", "total revenue", "net revenue", "net sales", "total net sales", "revenues", "us-gaap:Revenues"]','USD_millions','Top-line revenue for the reporting period. Used as the denominator in the capex/revenue efficiency ratio.');
INSERT INTO "metric_definitions" VALUES('operating_cash_flow','Net cash provided by operating activities','["ocf", "operating cash flow", "cash from operations", "cash flow from operations", "net cash provided by operating activities", "net cash from operating activities", "us-gaap:NetCashProvidedByOperatingActivities"]','USD_millions','Cash generated by the business''s core operations before investing or financing activity. Used as the denominator in the capex/OCF efficiency ratio.');
CREATE TABLE schema_version (
                version    INTEGER PRIMARY KEY,
                applied_at TEXT NOT NULL
            );
INSERT INTO "schema_version" VALUES(1,'2026-04-09T17:44:06+00:00');
CREATE TABLE source_documents (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker            TEXT NOT NULL REFERENCES companies(ticker),
    form_type         TEXT NOT NULL CHECK(form_type IN ('10-K', '10-Q', '20-F', 'HK-AR', 'HK-IR')),
    filing_date       TEXT NOT NULL,   -- ISO date
    period_of_report  TEXT NOT NULL,   -- ISO date
    fiscal_year       INTEGER NOT NULL,
    period_token      TEXT NOT NULL CHECK(period_token IN ('AR', 'Q1', 'Q2', 'Q3', 'H1', 'H2')),
    sha256            TEXT NOT NULL UNIQUE,
    raw_path          TEXT NOT NULL,
    canonical_path    TEXT,            -- null until organize-sources runs
    source            TEXT NOT NULL CHECK(source IN ('sec_edgar', 'hkex')),
    source_url        TEXT NOT NULL,
    accession_number  TEXT,            -- SEC only
    fetched_at        TEXT NOT NULL,
    fetcher_version   TEXT NOT NULL,
    protocol_version  TEXT NOT NULL,
    UNIQUE(ticker, form_type, period_of_report)
);
INSERT INTO "source_documents" VALUES(1,'MSFT','10-K','2025-07-30','2025-06-30',2025,'AR','99d693f6c1544144ebeee92954f151a85bc62111837530a42855953bc01d0bbe','data/_sources/MSFT/_raw/msft-20250630.htm','data/_sources/MSFT/2025/[30.07.2025][MSFT][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/789019/000095017025100235/msft-20250630.htm','0000950170-25-100235','2026-04-10T02:30:00+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(2,'AMZN','10-K','2026-02-06','2025-12-31',2025,'AR','beb1bfc28558135e76882db0cf36ba72a1ab44e2144fe37534f4da1e120ddb57','data/_sources/AMZN/_raw/amzn-20251231.htm','data/_sources/AMZN/2025/[06.02.2026][AMZN][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1018724/000101872426000004/amzn-20251231.htm','0001018724-26-000004','2026-04-10T10:31:39+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(3,'GOOGL','10-K','2026-02-05','2025-12-31',2025,'AR','c2f6301004f35411a20611c14ff01d80a85c0bcbab6053c80d8cc7f6fc747161','data/_sources/GOOGL/_raw/goog-20251231.htm','data/_sources/GOOGL/2025/[05.02.2026][GOOGL][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1652044/000165204426000018/goog-20251231.htm','0001652044-26-000018','2026-04-10T10:31:40+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(4,'META','10-K','2026-01-29','2025-12-31',2025,'AR','97d1a65e8f28c8d2878a1f73218b89f8da3be83e6517c5cffdd81845c8ce40be','data/_sources/META/_raw/meta-20251231.htm','data/_sources/META/2025/[29.01.2026][META][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1326801/000162828026003942/meta-20251231.htm','0001628280-26-003942','2026-04-10T10:31:41+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(5,'ORCL','10-K','2025-06-18','2025-05-31',2025,'AR','76d67d94d2168379120f9232387f7cb58fe65159e5c4743c470d7fbeee874835','data/_sources/ORCL/_raw/orcl-20250531.htm','data/_sources/ORCL/2025/[18.06.2025][ORCL][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1341439/000095017025087926/orcl-20250531.htm','0000950170-25-087926','2026-04-10T10:31:44+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(6,'BABA','20-F','2025-06-26','2025-03-31',2025,'AR','7959467eb4e32c27af13f2804aa4d0a7d0d6f49118f2a440b11d12e55eed4c46','data/_sources/BABA/_raw/baba-20250331.htm','data/_sources/BABA/2025/[26.06.2025][BABA][AR][20-F].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1577552/000095017025090161/baba-20250331.htm','0000950170-25-090161','2026-04-10T10:31:46+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(7,'BIDU','20-F','2026-03-17','2025-12-31',2025,'AR','16a242f31d42b99f202abf7b51317fbc0223732f9136f6f9ec4fe813f2e17ff5','data/_sources/BIDU/_raw/d38065d20f.htm','data/_sources/BIDU/2025/[17.03.2026][BIDU][AR][20-F].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1329099/000119312526109289/d38065d20f.htm','0001193125-26-109289','2026-04-10T10:31:48+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(8,'GDS','20-F','2025-04-28','2024-12-31',2024,'AR','c4f419260120887c9b701420a79902557cd9421225785a0e8d4215ae659d2b7c','data/_sources/GDS/_raw/gds-20241231x20f.htm','data/_sources/GDS/2024/[28.04.2025][GDS][AR][20-F].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1526125/000141057825000935/gds-20241231x20f.htm','0001410578-25-000935','2026-04-10T10:31:50+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(9,'CRWV','10-K','2026-03-02','2025-12-31',2025,'AR','c796cf3da3deaf213561a54b731af74526ff72fc854fde005591b0b1880ed1fc','data/_sources/CRWV/_raw/crwv-20251231.htm','data/_sources/CRWV/2025/[02.03.2026][CRWV][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1769628/000176962826000104/crwv-20251231.htm','0001769628-26-000104','2026-04-10T10:31:51+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(10,'APLD','10-K','2025-07-30','2025-05-31',2025,'AR','70bdc8e48e8a7d296e29c84e656f575e1f294f2977cd1a27ab1767ea1caa495e','data/_sources/APLD/_raw/apld-20250531.htm','data/_sources/APLD/2025/[30.07.2025][APLD][AR][10-K].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1144879/000114487925000021/apld-20250531.htm','0001144879-25-000021','2026-04-10T10:31:53+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(11,'IREN','20-F','2024-08-28','2024-06-30',2024,'AR','f3333fa476c97bc8c1b6a5e069a3a3a9708e49e13e22dd65be400315409a45ab','data/_sources/IREN/_raw/iren-20240630.htm','data/_sources/IREN/2024/[28.08.2024][IREN][AR][20-F].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1878848/000162828024038677/iren-20240630.htm','0001628280-24-038677','2026-04-10T10:31:55+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(12,'NBIS','20-F','2025-04-30','2024-12-31',2024,'AR','7edf65f79601be53a61de4bdbdbe954d5671c0c686d6d5bcbca8a091cf17277a','data/_sources/NBIS/_raw/nbis-20241231x20f.htm','data/_sources/NBIS/2024/[30.04.2025][NBIS][AR][20-F].htm','sec_edgar','https://www.sec.gov/Archives/edgar/data/1513845/000155837025005991/nbis-20241231x20f.htm','0001558370-25-005991','2026-04-10T10:31:56+00:00','0.1.0','0.1.0-draft');
INSERT INTO "source_documents" VALUES(13,'0700','HK-AR','2026-04-09','2025-12-31',2025,'AR','d19f183452e9b8d0c47bcb7543dcbf435b585b2610759b42c0cba7c13f7361c7','data/_sources/0700/_raw/2026040901232_c.pdf','data/_sources/0700/2025/[09.04.2026][0700][AR][HK-AR].pdf','hkex','https://www1.hkexnews.hk/listedco/listconews/sehk/2026/0409/2026040901232_c.pdf',NULL,'2026-04-10T11:56:49+00:00','0.1.0','0.1.0-draft');
CREATE TABLE validation_results (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    extraction_id INTEGER NOT NULL REFERENCES extractions(id),
    check_name    TEXT NOT NULL,       -- 'provenance_substring' | 'range_check' | etc
    passed        INTEGER NOT NULL CHECK(passed IN (0, 1)),
    details       TEXT,                 -- JSON
    checked_at    TEXT NOT NULL
);
CREATE INDEX idx_source_documents_ticker_period
    ON source_documents(ticker, period_of_report);
CREATE INDEX idx_extractions_metric
    ON extractions(metric_key);
CREATE INDEX idx_validation_results_extraction
    ON validation_results(extraction_id);
CREATE INDEX idx_audit_log_ts
    ON audit_log(ts);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('audit_log',34);
INSERT INTO "sqlite_sequence" VALUES('source_documents',13);
COMMIT;
