-- Auto-generated by capex.db.dump — do not edit by hand.
-- Regenerated on every successful DB mutation.
-- Source of truth: data/db/capex.db

BEGIN TRANSACTION;
CREATE TABLE audit_log (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ts           TEXT NOT NULL,
    actor        TEXT NOT NULL,         -- skill name + version, e.g. "sync-companies@0.0.1"
    action       TEXT NOT NULL,         -- e.g. "companies_upsert"
    target_table TEXT NOT NULL,
    target_id    INTEGER,
    payload      TEXT                   -- JSON of what changed
);
INSERT INTO "audit_log" VALUES(1,'2026-04-09T17:47:23+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 1, "total": 1, "updated": 0, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(2,'2026-04-09T17:47:23+00:00','sync-metric-definitions@0.0.1','metric_definitions_sync','metric_definitions',NULL,'{"deleted": 0, "inserted": 5, "total": 5, "updated": 0, "yaml_path": "data/seeds/metric_definitions.yaml"}');
INSERT INTO "audit_log" VALUES(3,'2026-04-09T17:47:58+00:00','sync-companies@0.0.1','companies_sync','companies',NULL,'{"deleted": 0, "inserted": 0, "total": 1, "updated": 1, "yaml_path": "data/_sources/_identity.yaml"}');
INSERT INTO "audit_log" VALUES(4,'2026-04-09T17:47:58+00:00','sync-metric-definitions@0.0.1','metric_definitions_sync','metric_definitions',NULL,'{"deleted": 0, "inserted": 0, "total": 5, "updated": 5, "yaml_path": "data/seeds/metric_definitions.yaml"}');
CREATE TABLE companies (
    ticker                TEXT PRIMARY KEY,
    name                  TEXT NOT NULL,
    preferred_source      TEXT NOT NULL CHECK(preferred_source IN ('sec_edgar', 'hkex')),
    edgar_cik             TEXT,
    hkex_stock_code       TEXT,
    fiscal_year_end_month INTEGER NOT NULL CHECK(fiscal_year_end_month BETWEEN 1 AND 12),
    synced_at             TEXT NOT NULL
);
INSERT INTO "companies" VALUES('MSFT','Microsoft Corporation','sec_edgar','0000789019',NULL,6,'2026-04-09T17:47:58+00:00');
CREATE TABLE extractions (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    source_document_id INTEGER NOT NULL REFERENCES source_documents(id),
    metric_key         TEXT NOT NULL REFERENCES metric_definitions(key),
    value              REAL,            -- nullable for "not disclosed"
    value_text         TEXT,            -- raw text as it appears in the filing
    unit               TEXT NOT NULL,
    quote              TEXT NOT NULL,
    locator_page       INTEGER,
    locator_section    TEXT,
    extraction_type    TEXT NOT NULL CHECK(extraction_type IN ('direct', 'inferred', 'derived')),
    confidence         REAL,
    extracting_model   TEXT NOT NULL,
    protocol_version   TEXT NOT NULL,
    extracted_at       TEXT NOT NULL,
    UNIQUE(source_document_id, metric_key, extracting_model)
);
CREATE TABLE golden_facts (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker            TEXT NOT NULL,
    period            TEXT NOT NULL,
    metric_key        TEXT NOT NULL,
    expected_value    REAL,
    expected_unit     TEXT NOT NULL,
    source_doc_sha256 TEXT NOT NULL,
    note              TEXT,
    UNIQUE(ticker, period, metric_key)
);
CREATE TABLE metric_definitions (
    key          TEXT PRIMARY KEY,
    label        TEXT NOT NULL,
    aliases      TEXT NOT NULL,        -- JSON array
    unit_default TEXT NOT NULL,
    description  TEXT
);
INSERT INTO "metric_definitions" VALUES('capital_expenditures','Capital expenditures','["capex", "capital expenditure", "capital expenditures", "purchases of property and equipment", "additions to property and equipment", "purchases of property, plant and equipment", "property and equipment additions", "investments in property and equipment"]','USD_millions','Cash outflows for purchases of property, plant, and equipment. Typically reported in the investing activities section of the cash flow statement. This is the headline capex figure.');
INSERT INTO "metric_definitions" VALUES('depreciation_amortization','Depreciation and amortization','["d&a", "depreciation", "depreciation and amortization", "depreciation, amortization and accretion", "depreciation and amortization expense"]','USD_millions','Non-cash charge reflecting the periodic expense of long-lived assets. Often reported alongside capex as a proxy for asset base turnover.');
INSERT INTO "metric_definitions" VALUES('property_plant_equipment_net','Property, plant and equipment, net','["ppe", "pp&e", "property and equipment net", "property, plant and equipment, net", "net property and equipment"]','USD_millions','Balance sheet carrying value of long-lived tangible assets after accumulated depreciation. The stock companion to capex (flow) and D&A (flow).');
INSERT INTO "metric_definitions" VALUES('revenue','Total revenue','["revenue", "total revenue", "net revenue", "net sales", "total net sales", "revenues"]','USD_millions','Top-line revenue for the reporting period. Used as the denominator in the capex/revenue efficiency ratio.');
INSERT INTO "metric_definitions" VALUES('operating_cash_flow','Net cash provided by operating activities','["ocf", "operating cash flow", "cash from operations", "cash flow from operations", "net cash provided by operating activities", "net cash from operating activities"]','USD_millions','Cash generated by the business''s core operations before investing or financing activity. Used as the denominator in the capex/OCF efficiency ratio.');
CREATE TABLE schema_version (
                version    INTEGER PRIMARY KEY,
                applied_at TEXT NOT NULL
            );
INSERT INTO "schema_version" VALUES(1,'2026-04-09T17:44:06+00:00');
CREATE TABLE source_documents (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker            TEXT NOT NULL REFERENCES companies(ticker),
    form_type         TEXT NOT NULL CHECK(form_type IN ('10-K', '10-Q', '20-F', 'HK-AR', 'HK-IR')),
    filing_date       TEXT NOT NULL,   -- ISO date
    period_of_report  TEXT NOT NULL,   -- ISO date
    fiscal_year       INTEGER NOT NULL,
    period_token      TEXT NOT NULL CHECK(period_token IN ('AR', 'Q1', 'Q2', 'Q3', 'H1', 'H2')),
    sha256            TEXT NOT NULL UNIQUE,
    raw_path          TEXT NOT NULL,
    canonical_path    TEXT,            -- null until organize-sources runs
    source            TEXT NOT NULL CHECK(source IN ('sec_edgar', 'hkex')),
    source_url        TEXT NOT NULL,
    accession_number  TEXT,            -- SEC only
    fetched_at        TEXT NOT NULL,
    fetcher_version   TEXT NOT NULL,
    protocol_version  TEXT NOT NULL,
    UNIQUE(ticker, form_type, period_of_report)
);
CREATE TABLE validation_results (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    extraction_id INTEGER NOT NULL REFERENCES extractions(id),
    check_name    TEXT NOT NULL,       -- 'provenance_substring' | 'range_check' | etc
    passed        INTEGER NOT NULL CHECK(passed IN (0, 1)),
    details       TEXT,                 -- JSON
    checked_at    TEXT NOT NULL
);
CREATE INDEX idx_source_documents_ticker_period
    ON source_documents(ticker, period_of_report);
CREATE INDEX idx_extractions_metric
    ON extractions(metric_key);
CREATE INDEX idx_validation_results_extraction
    ON validation_results(extraction_id);
CREATE INDEX idx_audit_log_ts
    ON audit_log(ts);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('audit_log',4);
COMMIT;
