#!/usr/bin/env python3
"""Relabel BABA cloud_segment_revenue quarters from calendar → fiscal.

The `baba-cloud-6k@0.1.0` extractor was labeling quarters using the
CALENDAR-quarter convention (Q1=Jan-Mar, Q2=Apr-Jun, …) while every
other BABA metric (revenue, XBRL, 6-K press releases) uses the
FISCAL-quarter convention (Q1=Apr-Jun, Q2=Jul-Sep, …).

The interactive chart assumes fiscal labels everywhere and runs its
`_calendar_qtr_from_fy` translation accordingly — so BABA cloud's
calendar-labelled rows were getting double-translated, collisions
silently overwriting legitimate bars and the fiscal-Q4 ( = calendar
Q1) bar vanishing entirely.

This script fixes the data: for BABA cloud_segment_revenue, rotate
the period_type label on 6-K source rows and delete the
reconcile-derived rows (they'll be regenerated by `capex reconcile`).

Rotation (calendar → fiscal):
    Q1 (por Mar 31) → Q4   (fiscal Q4)
    Q2 (por Jun 30) → Q1   (fiscal Q1)
    Q3 (por Sep 30) → Q2   (fiscal Q2)
    Q4 (por Dec 31) → Q3   (fiscal Q3)

Usage:
    python scripts/relabel_baba_cloud_quarters.py           # dry-run
    python scripts/relabel_baba_cloud_quarters.py --apply   # commit
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from capex.db import Database

# Calendar → fiscal rotation
ROTATION = {
    ("Q1", 3): "Q4",      # Mar → fiscal Q4
    ("Q2", 6): "Q1",      # Jun → fiscal Q1
    ("Q3", 9): "Q2",      # Sep → fiscal Q2
    ("Q4", 12): "Q3",     # Dec → fiscal Q3
}

DERIVED_MODEL_PREFIX = "reconcile-derived"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true",
                    help="Commit changes (default: dry-run)")
    args = ap.parse_args()
    apply = args.apply

    db = Database()
    with db.connect() as conn:
        rows = conn.execute(
            """
            SELECT e.id, e.period_type, e.extracting_model, e.value, e.value_usd,
                   sd.ticker, sd.period_of_report, sd.fiscal_year, sd.form_type
            FROM extractions e
            JOIN source_documents sd ON e.source_document_id = sd.id
            WHERE sd.ticker = 'BABA' AND e.metric_key = 'cloud_segment_revenue'
            ORDER BY sd.fiscal_year, sd.period_of_report, e.period_type
            """
        ).fetchall()

    relabel: list[tuple[int, str, str, dict]] = []   # (id, old, new, context)
    delete: list[tuple[int, str, dict]] = []         # (id, reason, context)
    untouched: list[tuple[int, str, dict]] = []

    for r in rows:
        rid = r["id"]
        ptype = r["period_type"]
        model = r["extracting_model"] or ""
        por = r["period_of_report"]
        month = int(por[5:7]) if por else 0
        ctx = {
            "fy": r["fiscal_year"], "por": por, "ptype": ptype,
            "model": model, "value_usd": r["value_usd"],
        }
        if model.startswith(DERIVED_MODEL_PREFIX):
            # All reconcile-derived rows for BABA cloud are stale after
            # the relabel. Delete; reconcile will regenerate.
            delete.append((rid, "derived (will be regenerated)", ctx))
            continue
        if ptype == "FY":
            # Annual row — keep as-is.
            untouched.append((rid, "FY row", ctx))
            continue
        key = (ptype, month)
        new = ROTATION.get(key)
        if new is None:
            untouched.append((rid, f"no rotation for ({ptype},{month})", ctx))
            continue
        if new == ptype:
            untouched.append((rid, "already correct", ctx))
            continue
        relabel.append((rid, ptype, new, ctx))

    print(f"BABA cloud_segment_revenue rows in DB: {len(rows)}")
    print(f"  to relabel:  {len(relabel)}")
    print(f"  to delete:   {len(delete)}  (reconcile-derived; will be regenerated)")
    print(f"  untouched:   {len(untouched)}")
    print()

    if relabel:
        print("--- Relabel (first 20) ---")
        for rid, old, new, ctx in relabel[:20]:
            print(f"  id={rid:4d} FY{ctx['fy']} por={ctx['por']} "
                  f"{old} → {new}  (${ctx['value_usd'] or 0:,.0f}M)")
        if len(relabel) > 20:
            print(f"  ... and {len(relabel) - 20} more")
        print()

    if delete:
        print("--- Delete (reconcile-derived) ---")
        for rid, reason, ctx in delete[:20]:
            print(f"  id={rid:4d} FY{ctx['fy']} por={ctx['por']} {ctx['ptype']} "
                  f"${ctx['value_usd'] or 0:,.0f}M ({reason})")
        if len(delete) > 20:
            print(f"  ... and {len(delete) - 20} more")
        print()

    if not apply:
        print("DRY RUN — rerun with --apply to commit.")
        return 0

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    actor = "baba-cloud-relabel@1.0"
    with db.mutating() as conn:
        for rid, old, new, ctx in relabel:
            conn.execute(
                "UPDATE extractions SET period_type = ? WHERE id = ?",
                (new, rid),
            )
            conn.execute(
                """
                INSERT INTO audit_log
                    (ts, actor, action, target_table, target_id, payload)
                VALUES (?, ?, 'period_type_relabeled', 'extractions', ?, ?)
                """,
                (now, actor, rid, json.dumps({
                    "old": old, "new": new, "fy": ctx["fy"],
                    "por": ctx["por"], "reason": "calendar→fiscal for BABA cloud",
                }, sort_keys=True)),
            )
        for rid, reason, ctx in delete:
            # Remove dependent evidence rows first
            conn.execute(
                "DELETE FROM extraction_evidence WHERE extraction_id = ?",
                (rid,),
            )
            conn.execute(
                "DELETE FROM validation_results WHERE extraction_id = ?",
                (rid,),
            )
            conn.execute("DELETE FROM extractions WHERE id = ?", (rid,))
            conn.execute(
                """
                INSERT INTO audit_log
                    (ts, actor, action, target_table, target_id, payload)
                VALUES (?, ?, 'extraction_deleted', 'extractions', ?, ?)
                """,
                (now, actor, rid, json.dumps({
                    "reason": reason, "fy": ctx["fy"], "por": ctx["por"],
                    "ptype": ctx["ptype"], "value_usd": ctx["value_usd"],
                }, sort_keys=True)),
            )

    print(f"Committed: {len(relabel)} relabeled, {len(delete)} deleted.")
    print("Run `capex reconcile --ticker BABA --metric cloud_segment_revenue --apply`"
          " to regenerate derived rows.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
