"""SQLite binary → SQL dump for diffable commits.

The binary .db file is the runtime; dump.sql is what humans actually
review in PRs. Every mutating operation regenerates the dump atomically
on successful commit (see Database.mutating()).

Why dump at all:
    * `git diff` on a binary .db is useless. A plaintext dump gives
      reviewers a line-by-line view of what a DB-mutating commit did.
    * The dump is also a rebuild path: when the binary outgrows its
      welcome, we can drop it entirely and rebuild on clone from the dump.
    * sqlite3.iterdump() is deterministic: tables come out in creation
      order, rows in insertion order, and statement syntax is stable. So
      identical DB states produce byte-identical dumps, which keeps git
      history clean.

Why not `sqlite3 capex.db .dump`:
    * No shelling out — stdlib iterdump() does the same thing without
      needing the sqlite3 CLI on the path.
    * Fewer dependencies, more portable across environments (WSL, CI,
      macOS, containers).
"""
from __future__ import annotations

import sqlite3
from pathlib import Path


def dump_to_sql(db_path: Path, dump_path: Path) -> None:
    """Write a complete SQL dump of db_path to dump_path, atomically.

    Uses tmp-then-rename so a reader or a killed process never observes
    a half-written dump file. The temp file lives in the same directory
    as the target so the final rename is a cheap metadata op (same
    filesystem guaranteed).
    """
    dump_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = dump_path.with_name(dump_path.name + ".tmp")

    conn = sqlite3.connect(db_path)
    try:
        with tmp_path.open("w", encoding="utf-8", newline="\n") as f:
            f.write("-- Auto-generated by capex.db.dump — do not edit by hand.\n")
            f.write("-- Regenerated on every successful DB mutation.\n")
            f.write("-- Source of truth: data/db/capex.db\n\n")
            for line in conn.iterdump():
                f.write(line)
                f.write("\n")
    finally:
        conn.close()

    tmp_path.replace(dump_path)
